### ISSUE TITLE
Shared build

### ISSUE THREAD

**Issue by egorpugin** [coding3d/small3d#34]
Hi,

As I noticed, you don't have support for linking small3d dynamically.
Is it true? Any plans on this?

**Comment by coding3d** [comment]
Sure! We can do that. I just never thought about it. :grimacing:
I'll prepare a version and let you know. It shouldn't take that long.
If I may ask, why is it important?

**Comment by egorpugin** [comment]
Yes, I'm working on C++ package manager. In some sense it's like conan, but sources are the first priority, not binaries (but they'll appear too a bit later). See https://cppan.org/
I've already added your project there, all its dependencies and right now I'm triying to build your example. It runs but fails to compile shader, trying to debug it right now, maybe some directory issues.
```
2016-09-13 17:53:03 - INFO: Using GLEW version 2.0.0
2016-09-13 17:53:03 - INFO: OpenGL version supported by machine: 4.5.13447 Compatibility Profile Context 16.300.2311.0
2016-09-13 17:53:03 - INFO: Ready for OpenGL 3.3
2016-09-13 17:53:03 - INFO: Renderer destructor running
2016-09-13 17:53:03 - ERROR: Failed to compile shader:

Info: ═¤¤¤¤

```

Your project is at https://cppan.org/pvt.cppan.demo.coding3d.small3d/version/1.0.4
You can see all its dependencies and some other stuff.

---
> If I may ask, why is it important?
And I just tried to build its with usage of shared libs, but your project is static only atm.
No worries, CPPAN can handle it too. :) See at the bottom of your project's page line `Spec file: cppan.yml - Show`,click it and you'll see `static_only: true` statement.

The ultimate goal is to build your project with one command: `cppan --build main.cpp`. :)

**Comment by egorpugin** [comment]
Oh, it looks like the whole shareds directory is missing.

**Comment by coding3d** [comment]
Alright :) That looks interesting. I'll be watching this project. Indeed the shaders are supposed to be in resources/shaders by default, unless the programmer specifies something different.

**Comment by coding3d** [comment]
Either way, I'll make sure shared builds work and report back :)

**Comment by coding3d** [comment]
In the meantime, let me know if you need any help with small3d whatsoever.

**Comment by egorpugin** [comment]
It works now. Sound is there, all looks good.
http://imgur.com/zdJcW51
I'll post here a simple example of usage of your library with CPPAN.
Have to update client binaries first (did significant fixes).

**Comment by egorpugin** [comment]
By the way.
I dont know much about conan, but...

With CPPAN you can do a magick trick.
If you add `CPPAN_EXPORT` to every symbol you'd like to export, CPPAN will handle it for you. On any system (win32, macos, *nix), with any build config (static, shared) and whatever here makes sense.

**Comment by coding3d** [comment]
Sounds good! I'll give it a try and see how it works :+1:

**Comment by coding3d** [comment]
Thanks for placing small3d there by the way :smile:

**Comment by egorpugin** [comment]
As you see, it's only in demo namespace.
If you bring there your projects officially, they'll be in pvt.your_name_here.*

**Comment by coding3d** [comment]
Sure, why not! By the way, I read in your documentation that you only support CMake for the time being. How did you get libogg there for example? It doesn't have a CMakeLists.txt as far as I know...

**Comment by egorpugin** [comment]
CMake for building YOUR projects.
For CPPAN projects I prefer raw source files.
That's one of the initial goals and ideas.
Just put bunch of your sources to CPPAN and it will handle them.
Fire and forget in some sense.

**Comment by egorpugin** [comment]
See spec file at the bottom
https://cppan.org/pvt.cppan.demo.xiph.libogg/version/1.3.2
Just regex your files and fire. :)

**Comment by egorpugin** [comment]
CPPAN should simplify C++, C++ dependencies, C++ libraries burden a lot.

**Comment by egorpugin** [comment]
Originally CPPAN targeted upcoming? C++20 Modules.
But it proofed that it wors now too.
---
With modules you will have only your sources, no dll exports and other stuff. Build system + compiler will handle them all. And CPPAN will handle needed dependencies for you.
CPPAN is designed to store sources, as with modules compile times will be very small.

**Comment by coding3d** [comment]
That's quite a time saver. Alright then. I'll register and give it a go.

**Comment by egorpugin** [comment]
Ok, I've updated client, so you could check it.
https://github.com/cppan/small3d_example

**Comment by coding3d** [comment]
That worked pretty well. It's quite impressive how it doesn't need any configuration files.

**Comment by egorpugin** [comment]
Actually config is inlined into main.cpp 
https://github.com/cppan/small3d_example/blob/master/avoidTheBug/main.cpp
because we need somehow specify our deps, build files.
Also you can see there a -std flag for non-msvc builds.

**Comment by coding3d** [comment]
Still, it spares you a lot of work. I've noticed on Windows that there's a warning about -std=c++11 not being recognised. It's not a big deal but maybe there should be a condition or something about which flags are used where?

**Comment by coding3d** [comment]
Also another question, when you set up small3d on cppan, did you need to change my include statements to avoid errors like this?

`fatal error: 'Text.hpp' file not found #include "Text.hpp"`

I mean, did you convert the statements to something like #include "small3d/Text.hpp"?
I am building small3d, having copy-pasted the cppan.yml file you used for the demo package.

**Comment by egorpugin** [comment]
No, includes are untouched.
Local building of projects with ONLY cppan are not finished yet, so the errors are natural.
Keep building your projects with CMake for some time more.

At the moment cppan might help you:
1. In building of simple projects like from example.
2. In dependencies handling from remote site for your CMake project.

**Comment by coding3d** [comment]
Cool, good to know :) Either way I'll keep working on it. It seems to be quite a promising project. 👍

**Comment by egorpugin** [comment]
One more note here.
The question about building whole projects with CPPAN is very subtle.
If it's possible, people will ask about doc building, testings, benchmarking etc.
I do not have these answers at the moment.
And I don't think actually I'll be able to implement all this stuff in near future.

Better way (and for you also) is to include CPPAN to your cmake project. Like you did with conan.
Example can be found here https://github.com/cppan/tesseract_example/tree/master/with_cmake

In brief, you add `cppan.yml` to root folder, add `add_subdirectory(cppan)` to root CMakeFiles.txt (after your compiler settings, but before other subdirs and any targets), `target_link_libraries(your_target cppan)` or `target_link_libraries(your_target pvt.cppan.name.of.dependent.project-version)`, call `cppan` without args in this dir before cmake call, call `cmake` in any form you need.

**Comment by coding3d** [comment]
Got it! I'll do it like that.
I'm not sure if a package manager has to do all that. Imho it's better to focus on managing packages. The rest can be better taken care of on a CI server or something like that...

**Comment by coding3d** [comment]
Hi Egor,

Given the fact that the cppan small3d compilation worked in the end. Do you see any reason why you might need a shared build for dynamic linking? I can do it but it seems to be a bit more involved than I would like for the time being...

**Comment by egorpugin** [comment]
No, it's not so important at all.

But... :) again I have a simple solution here in case you'd like to try it.
You know, as I wrote earlier shared builds involve such things like OS specific stuff (export), export/import stuff and some other thing.
No-brainer and very fun experimental solution here is to create a separate branch, add to each symbol CPPAN_EXPORT - not so hard and upload this branch to CPPAN.
So we could check it just from the branch - instead of requesting stable 2.*.* version, I could change it to `test_shared` branch and try it.

**Comment by coding3d** [comment]
Thanks Egor! CPPAN_EXPORT sounds very practical and I might use it for another project, but I am trying to keep the source and everything around small3d as simple as possible for whomever might be interested in it. So I avoid adding branches and symbols, unless they are needed for the functionality of the library (sorry :pensive: ).

Of course, having said that, if you would like to try CPPAN_EXPORT out with small3d, please feel free to fork the project. I don't mind at all :innocent:

**Comment by egorpugin** [comment]
Not a problem.
I did a test of CPPAN_EXPORT for me, you can find it here https://github.com/egorpugin/mfl1/blob/master/mfl1.h

Don't look at CPPAN_{PROLOG|EPILOG}.
They are needed if you want to automatically put all your stuff in pvt::your::cool::project namespace.
I consider these macros still experimental and wonder if they are  useful or not.
But I know with 100% sure that CPPAN_EXPORT is very useful.

**Comment by egorpugin** [comment]
Here is another example with different project dir structure https://github.com/egorpugin/mfl2/blob/master/include/mfl2.h with no prolog/epilog.

ps.
mfl stands for 'my favourite library'.

**Comment by coding3d** [comment]
:)
